import type { Metadata } from "next";
import { Epilogue, Poppins, Open_Sans } from "next/font/google";
import "./globals.css";
import StoreProvider from './storeProvider';

const epilogue = Epilogue({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={epilogue.className}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}